# https://aka.ms/yaml
trigger:
- master

strategy:
  matrix:
    windows-stable:
      imageName: 'windows-latest'
      rustup_toolchain: stable
    windows-beta:
      imageName: 'windows-latest'
      rustup_toolchain: beta
    windows-nightly:
      imageName: 'windows-latest'
      rustup_toolchain: nightly

    mac-stable:
      imageName: 'macos-latest'
      rustup_toolchain: stable
    mac-beta:
      imageName: 'macos-latest'
      rustup_toolchain: beta
    mac-nightly:
      imageName: 'macos-latest'
      rustup_toolchain: nightly

    linux-stable:
      imageName: 'ubuntu-latest'
      rustup_toolchain: stable
    linux-beta:
      imageName: 'ubuntu-latest'
      rustup_toolchain: beta
    linux-nightly:
      imageName: 'ubuntu-latest'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

steps:
- template: pipelines/install-rust.yml
  parameters:
    rustup_toolchain: $(rustup_toolchain)
- script: |
    rustc --version --verbose
    cargo build --verbose --all
    cargo test --verbose --all --no-run
  displayName: build

- script: |
    rustc --version --verbose
    cargo clippy --all-targets --all-features --all
  displayName: clippy

- script: |
    cargo test --verbose --all
  displayName: test

- script: |
    cargo doc --no-deps --verbose --all
  displayName: docs
