[package]
name = "spritec"
version = "0.1.0"
authors = [
  "Sunjay Varma <varma.sunjay@gmail.com>",
  "James Shi <jsjamesshi@gmail.com>",
  "Bill Chen <bchen.tcu@gmail.com>",
  "Mara Gagiu <mara.gagiu@gmail.com>",
]
edition = "2018"

[dependencies]
glium = "0.26.0-alpha6"
tobj = "0.1"
vek = { version = "0.9", features = ["serde"] }
# Keep this version synced with the version from vek
num-traits = "0.2"
# Keep this version synced with the version from vek
approx = "0.1.1"
image = "0.22"
gltf = "0.14"
structopt = "0.2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.3"
thiserror = "1.0"
interpolation = "0.2"

[profile.dev]
# Needed to make software rendering fast enough
opt-level = 3
