[package]
name = "spritec-preview"
version = "0.1.0"
authors = [
  "Sunjay Varma <varma.sunjay@gmail.com>",
  "James Shi <jsjamesshi@gmail.com>",
  "Bill Chen <bchen.tcu@gmail.com>",
  "Mara Gagiu <mara.gagiu@gmail.com>",
]
edition = "2018"

[dependencies]
spritec = { path = ".." }
euc = "0.2"
minifb = "0.11"
vek = "0.9"
